icons = "awesome"

[theme]
name = "plain"
[theme.overrides]
idle_bg      = "#26233a"
idle_fg      = "#6e6a86"
info_bg      = "#26233a"
good_bg      = "#26233a"
good_fg      = "#f6c177"
warning_bg   = "#26233a"
warning_fg   = "#c4a7e7"
critical_bg  = "#26233a"
critical_fg  = "#eb6f92"
separator_bg = "#26233a"
separator_fg = "#6e6a86"

# [[block]]
# block = "music"
# player = "spotify"
# buttons = ["play", "next"]
# on_collapsed_click = "spotify"

[[block]]
block = "custom"
command = "watson status | sed 's/ (.*/./'"
interval = 60

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 20
format = "%a %d/%m %R"
