[icons]
icons = "none"

[theme]
theme = "plain"
[theme.overrides]
idle_bg      = "#26233a"
idle_fg      = "#6e6a86"
info_bg      = "#26233a"
good_bg      = "#26233a"
good_fg      = "#f6c177"
warning_bg   = "#26233a"
warning_fg   = "#c4a7e7"
critical_bg  = "#26233a"
critical_fg  = "#eb6f92"
separator_bg = "#26233a"
separator_fg = "#6e6a86"

[[block]]
block = "custom"
# command = "watson report -Gcd | tail -n1 | cut -d ' ' -f 2-3"
# command = "watson status | sed 's/ (.*/./'"
command = "echo \"$(watson report -Gcd | tail -n1 | cut -d ' ' -f 2-3) - $(watson status | sed 's/ (.*/./')\""
interval = 20
[[block.click]]
button = "left"
update = true
sync = true
cmd = "watson-toggle"

[[block]]
block = "custom"
command = "pomo s"
interval = 20
[[block.click]]
button = "left"
update = true
sync = true
cmd = "pomo t"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 1

[[block]]
block = "time"
interval = 20
format = " $timestamp.datetime(f:'%a %d/%m %R') "
